CONFIG_GPIO=y
CONFIG_LOG=y

# CONFIG_BLINK_SPEED_250MS=y
# CONFIG_BLINK_SPEED_TIME_MS=1000 # becauuse the variable is hidden.

# Enable the LED Subsystem
CONFIG_LED_SUBSYSTEM=y

# Choose a default speed (triggers the exclusive choice)
CONFIG_LED_BLINK_SLEEP_TIME_1S=y

# Enable advanced settings and override default numerical values.
CONFIG_ADVANCED_LED=n
CONFIG_LED_BRIGHTNESS=100
CONFIG_LED_FADE_DURATION=500



